<div id="reply-approval" class="modal fade in">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title"><?= H(T('驳回审核请求')) ?></h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body" style="padding-top:20px;">
            <form id="reply-approval-form" method="POST" action="gini-ajax:ajax/approval/reply/<?= $approval->id ?>">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group form-group-lg">
                            <?php if (isset($form['_errors']['reason'])) { ?>
                            <span class="badge badge-danger pull-right">
                                <?= H($form['_errors']['reason']) ?>
                            </span>
                            <?php } ?>
                            <label class="control-label" for="reason"><?= H('驳回理由') ?></label>
                            <textarea id="reason" name="reason" type="text" class="form-control <?= isset($form['_errors']['reason']) ? 'is-invalid' : '' ?>" rows="3"/><?= $form['reason'] ?></textarea>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary btn-raised" form="reply-approval-form" type="submit"><i class="fa fa-reply fa-fw"></i> <?= H(T('驳回')) ?></button>
            <button class="btn btn-secondary btn-raised" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times fa-fw "></i><?= H(T('关闭')) ?></button>
        </div>
    </div>
</div>
</div>
<script data-ajax="true">
require(['main'], function($){

    var $modal = $('#reply-approval');
    $modal
    .on('hidden.bs.modal', function(){
        $modal.remove();
    })
    .modal();

    $('#reply-approval-form').on('ajax-success', function(){
        $modal
        .removeAttr('id').modal('hide')
        .find('[id]').removeAttr('id');
    });

});
</script>