<div class="container" id="login">
	<div class="row justify-content-md-center">
		<div class="col-xs-12 col-md-6 col-md-offset-3 login-title">
		</div>
	</div>
	<div class="row justify-content-md-center">
		<div class="col-xs-12 col-sm-12 col-md-4" id="login-box">
			<?= \Gini\Model\Alert::getMessage() ?>
			<div class="card">
				<div class="card-header">
					<?= T('天元内控系统')?>
				</div>
				<div class="card-body">
					<form method="POST" id="login-from">
						<div class="form-group">
							<input type="text" class="form-control <?= isset($form['_errors']['AuthToken']) ? 'is-invalid' : '' ?>" name="AuthToken" placeholder="用户名" id="AuthToken" autocomplete="off" value="<?= $form['AuthToken']?>" />
						</div>
						<div class="form-group">
							<input type="password" class="form-control <?= isset($form['_errors']['AuthCode']) ? 'is-invalid' : '' ?>" id="AuthCode" placeholder="密    码" name="AuthCode" autocomplete="off" />
						</div>
						<div class="form-group">
							<button type="submit" form="login-from" class="btn btn-info btn-block btn-raised login-from-btn"><?= H(T('登录')) ?></button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
