<div class="ownership_box">
    <h4 class="text-center"><?= \Gini\ORM\Building::$ownership_cert_type[1] ?></h4>
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text" id="">证号</span>
        </div>
        <?php $ownership = (array)$building->ownership[1]; ?>
        <input name="ownership[1][number]" type="text" class="form-control" value="<?= $ownership['number'] ?>" />
    </div>
    <div class="hr"></div>
    <table class="table table-sm table-bordered table-object">
        <tbody>
            <tr>
                <td colspan="2" class="disable">权利人</td>
                <td colspan="6">
                    <input name="ownership[1][owner]" type="text" class="form-control" value="<?= $ownership['owner'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">共有情况</td>
                <td colspan="6">
                    <input name="ownership[1][gyqk]" type="text" class="form-control" value="<?= $ownership['gyqk'] ?: '单独所有' ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">坐落</td>
                <td colspan="6">
                    <input name="ownership[1][zl]" type="text" class="form-control" value="<?= $ownership['zl'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">不动产单元号</td>
                <td colspan="6">
                    <input name="ownership[1][bdcdyh]" type="text" class="form-control" value="<?= $ownership['bdcdyh'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">权利类型</td>
                <td colspan="6">
                    <input name="ownership[1][qllx]" type="text" class="form-control" value="<?= $ownership['qllx'] ?: '国有建设用地使用权/房屋（构筑物）所有权' ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">权利性质</td>
                <td colspan="6">
                    <input name="ownership[1][qlxz]" type="text" class="form-control" value="<?= $ownership['qlxz'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">用途</td>
                <td colspan="6">
                    <input name="ownership[1][yt]" type="text" class="form-control" value="<?= $ownership['yt'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">面积</td>
                <td colspan="6">
                    <input name="ownership[1][mj]" type="text" class="form-control" value="<?= $ownership['mj'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">使用期限</td>
                <td colspan="6">
                    <input name="ownership[1][syqx]" type="text" class="form-control" value="<?= $ownership['syqx'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">权利其他状况</td>
                <td colspan="6">
                    <input name="ownership[1][qlqtzk]" type="text" class="form-control" value="<?= $ownership['qlqtzk'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">附记</td>
                <td colspan="6">
                    <input name="ownership[1][fj]" type="text" class="form-control" value="<?= $ownership['fj'] ?>" />
                </td>
            </tr>
        </tbody>
    </table>
</div>