<div class="input-group">
    <div class="input-group-prepend">
        <span class="input-group-text" id="">证号</span>
    </div>
    <input name="number" type="text" class="form-control" value="<?= $building->ownership['number'] ?>" />
</div>
<div class="hr"></div>
<table class="table table-sm table-bordered table-object">
    <tbody>
        <tr>
            <td class="disable">权利人</td>
            <td colspan="7">
                <input name="owner" type="text" class="form-control" value="<?= $building->ownership['owner'] ?>" />
            </td>
        </tr>
        <tr>
            <td class="disable">坐落</td>
            <td colspan="7">
                <input name="zl" type="text" class="form-control" value="<?= $building->ownership['zl'] ?>" />
            </td>
        </tr>
        <tr>
            <td class="disable">地号</td>
            <td colspan="7">
                <input name="dh" type="text" class="form-control" value="<?= $building->ownership['dh'] ?>" />
            </td>
        </tr>
        <tr>
            <td class="disable">图号</td>
            <td colspan="7">
                <input name="th" type="text" class="form-control" value="<?= $building->ownership['th'] ?>" />
            </td>
        </tr>
        <tr>
            <td rowspan="4" class="disable">土地状况</td>
            <td class="disable">权属性质</td>
            <td colspan="2">
                <input name="qsxz" type="text" class="form-control" value="<?= $building->ownership['qsxz'] ?: '国有' ?>" />
            </td>
            <td colspan="2" class="disable">用途</td>
            <td colspan="2">
                <input name="yt" type="text" class="form-control" value="<?= $building->ownership['yt'] ?: '城镇住宅用地' ?>" />
            </td>
        </tr>
        <tr>
            <td class="disable">使用权类型</td>
            <td colspan="7">
                <input name="syqlx" type="text" class="form-control" value="<?= $building->ownership['syqlx'] ?>" />
            </td>
        </tr>
        <tr>
            <td class="disable">终止日期</td>
            <td colspan="7">
                <input name="zzrq" type="text" class="form-control" value="<?= $building->ownership['zzrq'] ?>" />
            </td>
        </tr>
        <tr>
            <td class="disable">使用权面积</td>
            <td colspan="7">
                <input name="syqmj" type="text" class="form-control" value="<?= $building->ownership['syqmj'] ?>" />
            </td>
        </tr>
        <tr>
            <td rowspan="4" class="disable">房屋状况</td>
            <td class="disable">产别</td>
            <td colspan="6">
                <input name="cb" type="text" class="form-control" value="<?= $building->ownership['cb'] ?: '私产' ?>" />
            </td>
        </tr>
        <tr>
            <td class="disable">幢号</td>
            <td class="disable">房号</td>
            <td class="disable">结构</td>
            <td class="disable">房屋总层数</td>
            <td class="disable">所在层数</td>
            <td class="disable">建筑面积(m²)</td>
            <td class="disable">设计用途</td>
        </tr>
        <tr>
            <td><input name="fwzh" type="text" class="form-control" value="<?= $building->ownership['fwzh'] ?>" /></td>
            <td><input name="fwfh" type="text" class="form-control" value="<?= $building->ownership['fwfh'] ?>" /></td>
            <td><input name="fwjg" type="text" class="form-control" value="<?= $building->ownership['fwjg'] ?>" /></td>
            <td><input name="fwzcs" type="text" class="form-control" value="<?= $building->ownership['fwzcs'] ?>" /></td>
            <td><input name="fwszcs" type="text" class="form-control" value="<?= $building->ownership['fwszcs'] ?>" /></td>
            <td><input name="fwjzmj" type="text" class="form-control" value="<?= $building->ownership['fwjzmj'] ?>" /></td>
            <td><input name="fwsjyt" type="text" class="form-control" value="<?= $building->ownership['fwsjyt'] ?>" /></td>
        </tr>
        <tr>
            <td colspan="7">
                <div class="form-inline">
                    共有人
                    <input name="sum" type="text" class="form-control" value="<?= (int)$building->ownership['sum'] ?>" size="4" />等
                    <input name="sum_name" type="text" class="form-control" value="<?= $building->ownership['sum_name'] ?>" size="8" />人，共有权证号自
                    <input name="cert_start" type="text" class="form-control" value="<?= $building->ownership['cert_start'] ?>" size="8" />至
                    <input name="cert_end" type="text" class="form-control" value="<?= $building->ownership['cert_end'] ?>" size="8" />
                </div>
            </td>
        </tr>
        <tr>
            <td class="disable">记事</td>
            <td colspan="7">
                <input name="js" type="text" class="form-control" value="<?= $building->ownership['js'] ?>" />
            </td>
        </tr>
    </tbody>
</table>