<div class="ownership_box">
    <h4 class="text-center"><?= \Gini\ORM\Building::$ownership_cert_type[3] ?></h4>
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text" id="">证号</span>
        </div>
        <?php $ownership = (array)$building->ownership[3]; ?>
        <input name="ownership[3][number]" type="text" class="form-control" value="<?= $ownership['number'] ?>" />
    </div>
    <div class="hr"></div>
    <table class="table table-sm table-bordered table-object">
        <tbody>
            <tr>
                <td class="disable">权利人</td>
                <td colspan="7">
                    <input name="ownership[3][owner]" type="text" class="form-control" value="<?= $ownership['owner'] ?>" />
                </td>
            </tr>
            <tr>
                <td class="disable">坐落</td>
                <td colspan="7">
                    <input name="ownership[3][zl]" type="text" class="form-control" value="<?= $ownership['zl'] ?>" />
                </td>
            </tr>
            <tr>
                <td class="disable">地号</td>
                <td colspan="7">
                    <input name="ownership[3][dh]" type="text" class="form-control" value="<?= $ownership['dh'] ?>" />
                </td>
            </tr>
            <tr>
                <td class="disable">图号</td>
                <td colspan="7">
                    <input name="ownership[3][th]" type="text" class="form-control" value="<?= $ownership['th'] ?>" />
                </td>
            </tr>
            <tr>
                <td rowspan="4" class="disable">土地状况</td>
                <td class="disable">权属性质</td>
                <td colspan="2">
                    <input name="ownership[3][qsxz]" type="text" class="form-control" value="<?= $ownership['qsxz'] ?: '国有' ?>" />
                </td>
                <td colspan="2" class="disable">用途</td>
                <td colspan="2">
                    <input name="ownership[3][yt]" type="text" class="form-control" value="<?= $ownership['yt'] ?: '城镇住宅用地' ?>" />
                </td>
            </tr>
            <tr>
                <td class="disable">使用权类型</td>
                <td colspan="7">
                    <input name="ownership[3][syqlx]" type="text" class="form-control" value="<?= $ownership['syqlx'] ?>" />
                </td>
            </tr>
            <tr>
                <td class="disable">终止日期</td>
                <td colspan="7">
                    <input name="ownership[3][zzrq]" type="text" class="form-control" value="<?= $ownership['zzrq'] ?>" />
                </td>
            </tr>
            <tr>
                <td class="disable">使用权面积</td>
                <td colspan="7">
                    <input name="ownership[3][syqmj]" type="text" class="form-control" value="<?= $ownership['syqmj'] ?>" />
                </td>
            </tr>
            <tr>
                <td rowspan="4" class="disable">房屋状况</td>
                <td class="disable">产别</td>
                <td colspan="6">
                    <input name="ownership[3][cb]" type="text" class="form-control" value="<?= $ownership['cb'] ?: '私产' ?>" />
                </td>
            </tr>
            <tr>
                <td class="disable">幢号</td>
                <td class="disable">房号</td>
                <td class="disable">结构</td>
                <td class="disable">房屋总层数</td>
                <td class="disable">所在层数</td>
                <td class="disable">建筑面积(m²)</td>
                <td class="disable">设计用途</td>
            </tr>
            <tr>
                <td><input name="ownership[3][fwzh]" type="text" class="form-control" value="<?= $ownership['fwzh'] ?>" /></td>
                <td><input name="ownership[3][fwfh]" type="text" class="form-control" value="<?= $ownership['fwfh'] ?>" /></td>
                <td><input name="ownership[3][fwjg]" type="text" class="form-control" value="<?= $ownership['fwjg'] ?>" /></td>
                <td><input name="ownership[3][fwzcs]" type="text" class="form-control" value="<?= $ownership['fwzcs'] ?>" /></td>
                <td><input name="ownership[3][fwszcs]" type="text" class="form-control" value="<?= $ownership['fwszcs'] ?>" /></td>
                <td><input name="ownership[3][fwjzmj]" type="text" class="form-control" value="<?= $ownership['fwjzmj'] ?>" /></td>
                <td><input name="ownership[3][fwsjyt]" type="text" class="form-control" value="<?= $ownership['fwsjyt'] ?>" /></td>
            </tr>
            <tr>
                <td colspan="7">
                    <div class="form-inline">
                        共有人
                        <input name="ownership[3][sum]" type="text" class="form-control" value="<?= (int)$ownership['sum'] ?>" size="4" />等
                        <input name="ownership[3][sum_name]" type="text" class="form-control" value="<?= $ownership['sum_name'] ?>" size="8" />人，共有权证号自
                        <input name="ownership[3][cert_start]" type="text" class="form-control" value="<?= $ownership['cert_start'] ?>" size="8" />至
                        <input name="ownership[3][cert_end]" type="text" class="form-control" value="<?= $ownership['cert_end'] ?>" size="8" />
                    </div>
                </td>
            </tr>
            <tr>
                <td class="disable">记事</td>
                <td colspan="7">
                    <input name="ownership[3][js]" type="text" class="form-control" value="<?= $ownership['js'] ?>" />
                </td>
            </tr>
        </tbody>
    </table>
</div>