<div class="ownership_box"  data-toggle="tooltip" title="#0121（房产证视图）">
    <h4 class="text-center"><?= \Gini\ORM\Building::$ownership_cert_type[4] ?></h4>
    <div class="input-group" data-toggle="tooltip" title="#0120">
        <div class="input-group-prepend">
            <span class="input-group-text" id="">证号</span>
        </div>
        <?php $ownership = (array)$building->ownership[4]; ?>
        <input name="ownership[4][number]" type="text" class="form-control" value="<?= $ownership['number'] ?>" />
    </div>
    <div class="hr"></div>
    <table class="table table-sm table-bordered table-object">
        <tbody>
            <tr>
                <td class="disable">共有权人</td>
                <td colspan="7">
                    <input name="ownership[4][owner]" type="text" class="form-control" value="<?= $ownership['owner'] ?>" />
                </td>
            </tr>
            <tr>
                <td class="disable">坐落</td>
                <td colspan="7">
                    <input name="ownership[4][zl]" type="text" class="form-control" value="<?= $ownership['zl'] ?>" />
                </td>
            </tr>
            <tr>
                <td class="disable">地号</td>
                <td colspan="7">
                    <input name="ownership[4][dh]" type="text" class="form-control" value="<?= $ownership['dh'] ?>" />
                </td>
            </tr>
            <tr>
                <td class="disable">图号</td>
                <td colspan="7">
                    <input name="ownership[4][th]" type="text" class="form-control" value="<?= $ownership['th'] ?>" />
                </td>
            </tr>
            <tr>
                <td class="disable">房地产权利持证人</td>
                <td colspan="7">
                    <input name="ownership[4][fdcqlczr]" type="text" class="form-control" value="<?= $ownership['fdcqlczr'] ?>" />
                </td>
            </tr>
            <tr>
                <td class="disable">房地产权证证号</td>
                <td colspan="7">
                    <input name="ownership[4][fdcqzzh]" type="text" class="form-control" value="<?= $ownership['fdcqzzh'] ?>" />
                </td>
            </tr>
            <tr>
                <td rowspan="2" class="disable">共有房屋土地状况</td>
                <td colspan="2" class="disable">房屋建筑面积</td>
                <td colspan="5">
                    <input name="ownership[4][fwjzmj]" type="text" class="form-control" value="<?= $ownership['fwjzmj'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">土地使用权面积</td>
                <td colspan="5">
                    <input name="ownership[4][tdsyqmj]" type="text" class="form-control" value="<?= $ownership['tdsyqmj'] ?>" />
                </td>
            </tr>
            <tr>
                <td class="disable">共有权人所占份额</td>
                <td colspan="7">
                    <input name="ownership[4][gyqrszfe]" type="text" class="form-control" value="<?= $ownership['gyqrszfe'] ?>" />
                </td>
            </tr>
            <tr>
                <td class="disable">记事</td>
                <td colspan="7">
                    <input name="ownership[4][js]" type="text" class="form-control" value="<?= $ownership['js'] ?>" />
                </td>
            </tr>
        </tbody>
    </table>
    <script>
    require(['main'], function($) {
        $('[data-toggle="tooltip"]').tooltip()
    });
    </script>
</div>