<div class="ownership_box" data-toggle="tooltip" title="#0121（房产证视图）">
    <h4 class="text-center"><?= \Gini\ORM\Building::$ownership_cert_type[6] ?></h4>
    <div class="input-group" data-toggle="tooltip" title="#0120">
        <div class="input-group-prepend">
            <span class="input-group-text" id="">证号</span>
        </div>
        <?php $ownership = (array)$building->ownership[6]; ?>
        <input name="ownership[6][number]" type="text" class="form-control" value="<?= $ownership['number'] ?>" />
    </div>
    <div class="hr"></div>
    <table class="table table-sm table-bordered table-object">
        <tbody>
            <tr>
                <td colspan="3" class="disable">房屋共有权证</td>
                <td colspan="6">
                    <input name="ownership[6][fwgyqz]" type="text" class="form-control" value="<?= $ownership['fwgyqz'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="3" class="disable">房屋所有权证持证人</td>
                <td colspan="6">
                    <input name="ownership[6][fwsyqczzr]" type="text" class="form-control" value="<?= $ownership['fwsyqczzr'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="3" class="disable">房屋所有权证号</td>
                <td colspan="6">
                    <input name="ownership[6][fwsyqzh]" type="text" class="form-control" value="<?= $ownership['fwsyqzh'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="3" class="disable">房屋坐落</td>
                <td colspan="6">
                    <input name="ownership[6][fwzl]" type="text" class="form-control" value="<?= $ownership['fwzl'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="3" class="disable">房屋建筑面积（平方米）</td>
                <td colspan="6">
                    <input name="ownership[6][fwjzmj]" type="text" class="form-control" value="<?= $ownership['fwjzmj'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="3" class="disable">共有权人所占份额</td>
                <td colspan="6">
                    <input name="ownership[6][gyqszfe]" type="text" class="form-control" value="<?= $ownership['gyqszfe'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="3" class="disable">附记</td>
                <td colspan="6">
                    <input name="ownership[6][fj]" type="text" class="form-control" value="<?= $ownership['fj'] ?>" />
                </td>
            </tr>
        </tbody>
    </table>
    <script>
    require(['main'], function($) {
        $('[data-toggle="tooltip"]').tooltip()
    });
    </script>
</div>