<div class="ownership_box">
    <h4 class="text-center"><?= \Gini\ORM\Building::$ownership_cert_type[8] ?></h4>
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text" id="">证号</span>
        </div>
        <?php $ownership = (array)$building->ownership[8]; ?>
        <input name="ownership[8][number]" type="text" class="form-control" value="<?= $ownership['number'] ?>" />
    </div>
    <div class="hr"></div>
    <table class="table table-sm table-bordered table-object">
        <tbody>
            <tr>
                <td colspan="2"  class="disable">土地使用权人</td>
                <td colspan="6">
                    <input name="ownership[8][owner]" type="text" class="form-control" value="<?= $ownership['owner'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2"  class="disable">座落</td>
                <td colspan="6">
                    <input name="ownership[8][fwzl]" type="text" class="form-control" value="<?= $ownership['fwzl'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">地号</td>
                <td colspan="2">
                    <input name="ownership[8][fwdh]" type="text" class="form-control" value="<?= $ownership['fwdh'] ?>" />
                </td>
                <td colspan="2" class="disable">图号</td>
                <td colspan="2">
                    <input name="ownership[8][fwth]" type="text" class="form-control" value="<?= $ownership['fwth'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">地类(用途)</td>
                <td colspan="2">
                    <input name="ownership[8][fwdlyt]" type="text" class="form-control" value="<?= $ownership['fwdlyt'] ?>" />
                </td>
                <td colspan="2" class="disable">取得价格</td>
                <td colspan="2">
                    <input name="ownership[8][fwqdjg]" type="text" class="form-control" value="<?= $ownership['fwqdjg'] ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">使用权类型</td>
                <td colspan="2">
                    <input name="ownership[8][syqlx]" type="text" class="form-control" value="<?= $ownership['syqlx'] ?>" />
                </td>
                <td colspan="2" class="disable">终止日期</td>
                <td colspan="2">
                    <input name="ownership[8][fwzzrq]" type="text" class="date form-control" placeholder="<?= H(T('0000-00-00'))?>" value="<?= date('Y-m-d', $ownership['fwzzrq'] ? strtotime($ownership['fwzzrq']) : time()) ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2" rowspan="2" class="disable">使用权面积</td>
                <td colspan="2" rowspan="2">
                    <div class="form-inline">
                        <input name="ownership[8][syqmj]" type="text" class="form-control" value="<?= $ownership['syqmj'] ?>" />m²
                    </div>
                </td>
                <td rowspan="2" class="disable">其中</td>
                <td class="disable">独用面积</td>
                <td colspan="2">
                    <div class="form-inline">
                        <input name="ownership[8][syqdymj]" type="text" class="form-control" value="<?= $ownership['syqdymj'] ?>" />m²
                    </div>
                </td>
            </tr>
            <tr>
                <td class="disable">分摊面积</td>
                <td colspan="2">
                    <div class="form-inline">
                        <input name="ownership[8][syqftmj]" type="text" class="form-control" value="<?= $ownership['syqftmj'] ?>" />m²
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2" class="disable">记事</td>
                <td colspan="6">
                    <input name="ownership[8][jsdes]" type="text" class="form-control" value="<?= $ownership['jsdes'] ?>" />
                </td>
            </tr>
        </tbody>
    </table>
    <script>
    require(['main'], function($){
        require(['bootstrap-datepicker', 'locales/bootstrap-datepicker.zh-CN', 'css!../css/bootstrap-datepicker'], function(){
            $('.date').datepicker({
                format: 'yyyy-mm-dd',
                language: 'zh-CN',
                minView: 'day'
            }) 
        })
    })
    </script>
</div>