<tr class="register-item">
    <td>
        <input name="items[<?= $index ?>][name]" class="form-control input-sm autocomplete" value="<?= H($item['name'])?:'';?>" />
    </td>
    <td class="text-center">
        <input name="items[<?= $index ?>][number]" class="form-control input-sm" value="<?= H($item['number'])?:'';?>" />
    </td>
    <td class="text-center">

    </td>
    <td class="text-center">
        
    </td>
    <td>
      <button class="btn btn-danger btn-sm delete-item"><i class="fa fa-minus"></i></button>
    </td>
</tr>