---
user.isAllowedTo[查看].user:
- callback:\Gini\Model\Role::userACL
user.isAllowedTo[添加].user:
- callback:\Gini\Model\Role::userACL
user.isAllowedTo[修改密码].user:
- callback:\Gini\Model\Role::userACL
user.isAllowedTo[修改基本信息].user:
- callback:\Gini\Model\Role::userACL
user.isAllowedTo[修改角色].user:
- callback:\Gini\Model\Role::userACL
user.isAllowedTo[删除用户].user:
- callback:\Gini\Model\Role::userACL
user.isAllowedTo[查看].role:
- callback:\Gini\Model\Role::roleACL
user.isAllowedTo[添加].role:
- callback:\Gini\Model\Role::roleACL
user.isAllowedTo[修改].role:
- callback:\Gini\Model\Role::roleACL
user.isAllowedTo[删除].role:
- callback:\Gini\Model\Role::roleACL
user.isAllowedTo[查看].group:
- callback:\Gini\Model\Role::groupACL
user.isAllowedTo[修改].group:
- callback:\Gini\Model\Role::groupACL
user.isAllowedTo[查看档案].project:
- callback:\Gini\Model\Role::archiveACL
user.isAllowedTo[查看档案项目].project:
- callback:\Gini\Model\Role::archiveACL
user.isAllowedTo[查看].template:
- callback:\Gini\Model\Role::templateACL
user.isAllowedTo[添加].template:
- callback:\Gini\Model\Role::templateACL
user.isAllowedTo[修改].template:
- callback:\Gini\Model\Role::templateACL
user.isAllowedTo[删除].template:
- callback:\Gini\Model\Role::templateACL
...