---
"001": "项目编号模板数据"
"002": "项目名称"
"003": "项目备注"
"004": "委托人姓名"
"005": "委托人住址"
"006": "估价目的"
"007": "建造年代"
"008": "物业管理"
"009": "坐落地址"
"010": "结构"
"011": "总层数"
"012": "所在层数"
"013": "朝向"
"014": "用途"
"015": "建筑面积"
"016": "户型"
"017": "层高"
"018": "是否有抵押"
"019": "附属物"
"020": "外墙"
"021": "装修部分-厅-外门"
"022": "装修部分-厅-内门"
"023": "装修部分-厅-外窗"
"024": "装修部分-厅-内窗"
"025": "装修部分-厅-墙面"
"026": "装修部分-厅-顶棚"
"027": "装修部分-厅-地面"
"028": "装修部分-卧室-墙面"
"029": "装修部分-卧室-顶棚"
"030": "装修部分-卧室-地面"
"031": "装修部分-卫生间-墙面"
"032": "装修部分-卫生间-顶棚"
"033": "装修部分-卫生间-地面"
"034": "装修部分-卫生间-设备"
"035": "装修部分-厨房-墙面"
"036": "装修部分-厨房-顶棚"
"037": "装修部分-厨房-地面"
"038": "装修部分-厨房-设备"
"039": "装修部分-阳台-墙面"
"040": "装修部分-阳台-地面"
"041": "设备设施-照明"
"042": "设备设施-一户一表"
"043": "设备设施-烟感报警系统"
"044": "设备设施-上下水"
"045": "设备设施-有线电视"
"046": "设备设施-自动喷淋系统"
"047": "设备设施-暖气"
"048": "设备设施-电话预留"
"049": "设备设施-中水"
"050": "设备设施-煤气"
"051": "设备设施-电梯"
"052": "设备设施-热水"
"053": "设备设施-对讲系统"
"054": "利用状况"
"055": "成新度"
"056": "四至东"
"057": "四至南"
"058": "四至西"
"059": "四至北"
"060": "周围配套情况"
"061": "估价对象其他信息"
"062": "容积率"
# "063": "估价结果视图"
"064": "估价结果-假定未设立法定优先受偿-总价小写"
"065": "估价结果-假定未设立法定优先受偿-总价大写"
"066": "估价结果-假定未设立法定优先受偿-单价小写"
"067": "估价结果-假定未设立法定优先受偿-单价大写"
"068": "估价结果-估价师知悉的法定优先受偿款-总额小写"
"069": "估价结果-估价师知悉的法定优先受偿款-总额大写"
"070": "估价结果-已抵押担保的债权数额-总额小写"
"071": "估价结果-已抵押担保的债权数额-总额大写"
"072": "估价结果-拖欠的建设工程价款-总额小写"
"073": "估价结果-拖欠的建设工程价款-总额大写"
"074": "估价结果-其他法定优先受偿款-总额小写"
"075": "估价结果-其他法定优先受偿款-总额大写"
"076": "估价结果-抵押价值-总价小写"
"077": "估价结果-抵押价值-总价大写"
"078": "估价结果-抵押价值-单价小写"
"079": "估价结果-抵押价值-单价大写"
# "080": "注册估价师视图"
"081": "作业期实地查勘日期"
"082": "估价作业期"
# "083": "技术报告-表1-比较因素条件说明表"
# "084": "技术报告-表2-比较因素条件指数表"
# "085": "技术报告-表3-比较因素条件修正系数表"
"086": "业务来源"
"087": "贷款银行"
"088": "审核表-估价委托人"
"089": "审核表-报告编号"
"090": "审核表-房屋所有权人"
"091": "审核表-项目坐落"
"092": "审核表-联系人"
"093": "审核表-联系电话"
"094": "审核表-项目案名"
"095": "审核表-委托日期"
"096": "审核表-价值时点"
"097": "审核表-领勘人"
"098": "审核表-建筑面积"
"099": "审核表-土地面积"
"0100": "审核表-估价目的"
"0101": "房龄"
"0102": "技术报告-交易情况"
"0103": "技术报告-交通通达度"
"0104": "技术报告-商业繁华度"
"0105": "技术报告-环境条件"
"0106": "技术报告-基础设施完备度"
"0107": "技术报告-公共设施完备度"
"0108": "技术报告-小区状况"
"0109": "技术报告-内部装修"
"0110": "技术报告-设施状况"
"0111": "机构名称"
"0112": "机构法定代表人"
"0113": "机构住所"
"0114": "机构统一社会信用代码"
"0115": "机构备案等级"
"0116": "机构证书编号"
"0117": "机构有效期限"
"0120": "产权证证号"
# "0121": "产权证视图"
# "0122": "租赁实例说明表视图"
# "0123": "估价对象与可比实例对比分析表视图"
"0124": "比较法评估单价"
"0125": "收益法-综合修正系数-可比实例1"
"0126": "收益法-综合修正系数-可比实例2"
"0127": "收益法-综合修正系数-可比实例3"
"0128": "收益法-交易租金-可比实例1"
"0129": "收益法-交易租金-可比实例2"
"0130": "收益法-交易租金-可比实例3"
"0131": "收益法-修正租金-估价对象"
"0132": "收益法-修正租金-可比实例1"
"0133": "收益法-修正租金-可比实例2"
"0134": "收益法-修正租金-可比实例3"
"0135": "收益法-有效出租面积（%）"
"0136": "收益法-年潜在毛收入（元/㎡）"
"0137": "收益法-银行存款利率（%）"
"0138": "收益法-其他收入（元/㎡）"
"0139": "收益法-年有效毛收入（元/㎡）"
"0140": "收益法-管理费（元/㎡）"
"0141": "收益法-建筑物重置成本（元/㎡）"
"0142": "收益法-维修费（元/㎡）"
"0143": "收益法-保险费（元/㎡）"
"0144": "收益法-税金（元/㎡）"
"0145": "收益法-运营费用（元/㎡）"
"0146": "收益法-净收益（元/㎡）"
"0147": "收益法-投资优惠率（%）"
"0148": "收益法-报酬率（%）"
"0149": "收益法-估价对象持有期"
"0150": "收益法-持有期间房地产价值"
"0151": "收益法-房价增长率（%）"
"0152": "收益法-计算单价（元/㎡）"
"0153": "收益法-单价（元/㎡）"
"0154": "收益法-总价值（元）"
"0155": "估价有效年限（年）"
"0156": "估价公司全称"
"0157": "估价公司地址"
"0158": "估价作业期开始时间"
"0159": "估价作业期截止时间"
"0160": "估价有效期截止时间"
"0161": "估价师名称"
"0162": "估价师列表"
"0163": "编号"
"0164": "评估价值(元)"
"0165": "抵押价值(元)"
"0166": "估价作业期（预评）"
"0167": "照明（多选框）"
"0168": "一户一表（多选框）"
"0169": "烟感报警系统（多选框）"
"0170": "上下水（多选框）"
"0171": "有线电视（多选框）"
"0172": "自动喷淋系统（多选框）"
"0173": "暖气（多选框）"
"0174": "宽带（多选框）"
"0175": "中水（多选框）"
"0176": "燃气（多选框）"
"0177": "电梯（多选框）"
"0178": "热水（多选框）"
"0179": "对讲系统（多选框）"
"0180": "院落（多选框）"
"0181": "阁楼（多选框）"
"0182": "露台（多选框）"
"0183": "地下库（多选框）"
"0184": "车库（多选框）"
"0185": "房本-房产所有人"
"0186": "房本-土地使用权类型"
"0187": "房本-土地使用权证号"
"0188": "房本-土地使用权面积"
"0189": "房本-出让土地使用权期限"
"0190": "装修（多选框）"
"0191": "估价师+注册号名称"
"0192": "出具报告时间(当前时间)"
"0193": "一层户数"
"0194": "剩余土地使用年限"
"0195": "是否对外出租"
"0196": "产权证书名称"
...