---
role:
  name: '权限管理' 
  perms:
  - '查看权限管理'
  - '添加角色'
  - '删除角色'
  - '修改角色权限'
user:
  name: '用户管理' 
  perms:
  - '查看用户模块'
  - '添加用户'
  - '删除用户'
  - '修改用户基本信息'
  - '修改用户角色'
record:
  name: '档案管理'
  perms:
  - '查看档案模块'
  - '修改所属档案模块'
  - '修改所有模块'
...