<table style="border: 1px solid black;border-spacing: 0px;width: 100%;">
<?php
        $building = $project->building;
        $calculat_table = (array)$project->calculat_table; 
    ?>
<tbody><tr>
<td colspan="7">
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt; font-weight: bold;">表2-比较因素条件指数表</span></p>
</td>
</tr>
<tr>
<td colspan="3">
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">影响因素</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">估价对象</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">实例一</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">实例二</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">实例三</span></p>
</td>
</tr>
<tr>
<td colspan="3">
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">交易价格（元/㎡）</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">待定</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt; color: #0000FF;"><?= $calculat_table['business_price_1']?> </span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt; color: #0000FF;"><?= $calculat_table['business_price_2']?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt; color: #0000FF;"><?= $calculat_table['business_price_3']?></span></p>
</td>
</tr>
<tr>
<td colspan="3">
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">市场状况</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_date_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_date_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_date_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_date_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td colspan="3">
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">交易情况</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_desc_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_desc_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_desc_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_desc_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td rowspan="18">
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">房地产状况</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</td>
<td rowspan="7">
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">区位状况</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">交通通达度</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_jttdd_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_jttdd_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_jttdd_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_jttdd_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">商业繁华度</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_syfhd_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_syfhd_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_syfhd_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_syfhd_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">环境条件（自然、人文、景观）</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_hjtj_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_hjtj_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_hjtj_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_hjtj_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">基础设施完备度</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_jcsswbd_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_jcsswbd_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_jcsswbd_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_jcsswbd_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">公共配套设施完备度</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_ggsswbd_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_ggsswbd_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_ggsswbd_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['business_ggsswbd_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">所在层/房屋总层数</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_lcdc_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt; color: #FF00FF;"><?= $calculat_table['gbys_lcdc_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt; color: #FF00FF;"><?= $calculat_table['gbys_lcdc_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt; color: #FF00FF;"><?= $calculat_table['gbys_lcdc_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">朝向</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_front_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_front_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_front_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_front_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td rowspan="8">
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">实物状况</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">成新率</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_precent_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_precent_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_precent_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_precent_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">物业管理</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_wygl_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_wygl_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_wygl_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_wygl_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">小区状况</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_ggbf_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_ggbf_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_ggbf_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_ggbf_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">建筑结构</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_structure_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_structure_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_structure_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_structure_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">房型</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_type_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_type_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_type_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_type_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">建筑面积（㎡）</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_jzmj_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_jzmj_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_jzmj_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_jzmj_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">内部装修</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt; color: 20190C0;"><?= $calculat_table['gbys_nbzx_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt; color: #FF00FF;"><?= $calculat_table['gbys_nbzx_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt; color: #FF00FF;"><?= $calculat_table['gbys_nbzx_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt; color: #FF00FF;"><?= $calculat_table['gbys_nbzx_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">设施状况</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_fssszk_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_fssszk_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_fssszk_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_fssszk_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td rowspan="3">
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">权益状况</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">产别</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_qycb_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_qycb_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_qycb_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_qycb_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">用途</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_yt_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_yt_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_yt_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_yt_zs_3'] ?></span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;">其他</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_qyqt_zs'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_qyqt_zs_1'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_qyqt_zs_2'] ?></span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-family: '仿宋'; font-size: 12pt;"><?= $calculat_table['gbys_qyqt_zs_3'] ?></span></p>
</td>
</tr>
</tbody></table>