<div class="hr"></div>
<div class="file-loading">
    <input id="input-attachment" name="input[]" type="file" multiple />
</div>
<div class="hr_2"></div>
<div class="hr_2"></div>
<div class="hr_2"></div>
<script>
require(['main'], function($) {
    require(['fileinput', 'theme/fa/theme', 'locales/zh', 'css!../css/fileinput'], function() {
        $("#input-attachment").fileinput({
            dropZoneEnabled: true,
            showClose: false,
            language: "zh",
            theme: "fa",
            uploadUrl: "ajax/project/uploadAttachment/<?= $project->id ?>",
            deleteUrl: "ajax/project/deleteAttachment/<?= $project->id ?>",
            initialPreviewDownloadUrl: '<?= URL("project/downloadAttachment/{$project->id}")?>/{key}',
            overwriteInitial: false,
            initialPreview: JSON.parse('<?= json_encode($project->attachments()) ?>'),
            initialPreviewConfig: JSON.parse('<?= json_encode($project->attachmentsConfig()) ?>'),
            preferIconicPreview: true,
            previewFileIconSettings: {
                'doc': '<i class="fa fa-file-word-o text-primary"></i>',
                'txt': '<i class="fa fa-file-text-o text-info"></i>',
                'xls': '<i class="fa fa-file-excel-o text-success"></i>',
                'ppt': '<i class="fa fa-file-powerpoint-o text-danger"></i>',
                'pdf': '<i class="fa fa-file-pdf-o text-danger"></i>',
                'zip': '<i class="fa fa-file-archive-o text-muted"></i>',
                'htm': '<i class="fa fa-file-code-o text-info"></i>',
                'txt': '<i class="fa fa-file-text-o text-info"></i>',
                'mov': '<i class="fa fa-file-movie-o text-warning"></i>',
                'mp3': '<i class="fa fa-file-audio-o text-warning"></i>',
                'jpg': '<i class="fa fa-file-photo-o text-danger"></i>', 
                'gif': '<i class="fa fa-file-photo-o text-warning"></i>', 
                'png': '<i class="fa fa-file-photo-o text-primary"></i>',
                'jpeg': '<i class="fa fa-file-photo-o text-danger"></i>' 
            },
            previewFileExtSettings: {
                'doc': function(ext) {
                    return ext.match(/(doc|docx)$/i);
                },
                'xls': function(ext) {
                    return ext.match(/(xls|xlsx)$/i);
                },
                'ppt': function(ext) {
                    return ext.match(/(ppt|pptx)$/i);
                },
                'zip': function(ext) {
                    return ext.match(/(zip|rar|tar|gzip|gz|7z)$/i);
                },
                'htm': function(ext) {
                    return ext.match(/(htm|html)$/i);
                },
                'mov': function(ext) {
                    return ext.match(/(avi|mpg|mkv|mov|mp4|3gp|webm|wmv)$/i);
                },
                'mp3': function(ext) {
                    return ext.match(/(mp3|wav)$/i);
                },
                'txt': function(ext) {
                    return ext.match(/(txt|ini|csv|java|php|js|css|numbers|pages|md)$/i);
                }
            },
            layoutTemplates: {
                actionZoom: ''
            }
        })
    })
})
</script>