<div class="hr_1"></div>
<ul class="nav nav-pills bg-dark" style="padding: 10px 5px;">
    <li class="nav-item">
        <a class="nav-link <?= $subCat == 'comparison' ? 'active' : '' ?>" href="<?= URL("/project/profile/{$project->id}/report/comparison")?>">比较法</a>
    </li>
    <li class="nav-item">
        <a class="nav-link <?= $subCat == 'income' ? 'active' : '' ?>" href="<?= URL("/project/profile/{$project->id}/report/income")?>">收益法</a>
    </li>
</ul>
<div class="hr_1"></div>
<?= V("projects/subtype/report/{$subCat}", [
    'project' => $project,
    'subCat' => $subCat,
    'form' => $form
]) ?>