<div class="hr"></div>
<form id="add-project-form" method="POST" action="gini-ajax:ajax/project/addTarget/<?= $project->id ?>">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group form-group-lg" data-toggle="tooltip" title="#006">
                <label class="control-label" for="target"><?= H('估价目的') ?></label>
                <textarea placeholder="<?= \Gini\Config::get('project.target') ?>" id="target" name="target" type="text" class="form-control"><?= $project->target ?></textarea>
            </div>
        </div>
    </div>
</form>
<?php if(_G('ME')->isAllowedTo('修改', $project)): ?>
<button class="btn btn-primary btn-raised" form="add-project-form" type="submit" name="edit"><i class="fa fa-edit fa-fw"></i> <?= H(T('保存信息')) ?></button>
<?php endif; ?>