<div class="hr"></div>
<form id="add-project-form" method="POST" action="gini-ajax:ajax/project/addUser/<?= $project->id ?>">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group form-group-lg">
                <label class="control-label" for="user_name"><?= H('姓名') ?></label>
                <input id="user_name" name="user_name" type="text" class="form-control" value="<?= $project->user_name ?>" />
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group form-group-lg">
                <label class="control-label" for="user_address"><?= H('地址') ?></label>
                <input id="user_address" name="user_address" type="text" class="form-control" value="<?= $project->user_address ?>" />
            </div>
        </div>
    </div>
</form>
<?php if(!$project->archived()): ?>
<button class="btn btn-primary btn-raised" name="supply"><i class="fa fa-plus fa-fw"></i> <?= H(T('补充信息')) ?></button>
<button class="btn btn-primary btn-raised" form="add-project-form" type="submit" name="edit"><i class="fa fa-edit fa-fw"></i> <?= H(T('修改信息')) ?></button>
<?php endif; ?>