<div id="project-description" class="modal fade in">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title"><?= H(T('私人备注信息')) ?></h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body" style="padding-top:20px;">
            <form id="project-description-form" method="POST" action="gini-ajax:ajax/project/description/<?= $project->id ?>">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group form-group-lg">
                            <label class="control-label" for="description"><?= H('备注信息') ?></label>
                            <textarea id="description" name="description" type="text" class="form-control" rows="3"/><?= $form['description'] ?></textarea>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary btn-raised" form="project-description-form" type="submit"><i class="fa fa-save fa-fw"></i> <?= H(T('更新')) ?></button>
            <button class="btn btn-secondary btn-raised" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times fa-fw "></i><?= H(T('关闭')) ?></button>
        </div>
    </div>
</div>
</div>
<script data-ajax="true">
require(['main'], function($){

    var $modal = $('#project-description');
    $modal
    .on('hidden.bs.modal', function(){
        $modal.remove();
    })
    .modal();

    $('#project-description-form').on('ajax-success', function(){
        $modal
        .removeAttr('id').modal('hide')
        .find('[id]').removeAttr('id');
    });

});
</script>