<div class="container-fluid">
    <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
        <?php 
            $me = _G('ME');
            if ($me->isAllowedTo('添加', 'project')):
        ?>
        <div class="btn-group" role="group" aria-label="First group">
            <button type="button" class="btn btn-dark" href="gini-ajax:AJAX/Project/Add" style="border-radius: 40px;width: 40px;">
                <i class="fa fa-plus"></i>
            </button>
        </div>
        <?php endif; ?>
        <form method="POST" action="<?= URL('/project')?>">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text" id="btnGroupAddon2">编号</div>
                </div>
                <input type="name" name="number" class="form-control" placeholder="请输入编号" aria-label="请输入编号" aria-describedby="btnGroupAddon2" value="<?= $form['number']?>">
            </div>
        </form>
    </div>
    <?= V('components/confirm') ?>
    <div class="hr"></div>
    <ul class="nav nav-tabs">
        <?php foreach(\Gini\ORM\Project::$TYPES as $key => $value):?>
            <li class="nav-item">
                <a class="nav-link <?= $type == $key ? 'active' : '' ?>" href="<?= URL('/project/'.$key) ?>"><?= $value ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="hr"></div>
    <table class="table table-light table-striped table-hover" id="project-table">
        <thead>
            <tr class="table-primary">
                <th scope="col">序号</th>
                <th scope="col">项目编号</th>
                <th scope="col">项目名称</th>
                <th scope="col">项目类型</th>
                <th scope="col">委托日期</th>
                <th scope="col">业务来源</th>
                <th scope="col">贷款银行</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
        <?php if (count($projects)): foreach($projects as $project): ?>
            <tr data-project-id="<?= intval($project->id) ?>">
                <td><span class="badge badge-dark"><?= str_pad($project->id, 6, '0', STR_PAD_LEFT) ?></span></td>
                <td><span class="badge badge-primary"><?= $project->number ?></span></td>
                <td><?= H($project->title) ?></td>
                <td><span class="badge <?= $project->type == 1 ? 'badge-dark' : 'badge-light' ?>"><?= \Gini\ORM\Project::$TYPES[$project->type] ?></span></td>
                <td><?= H(date('Y-m-d', strtotime($project->ctime))) ?></td>
                <td><?= H($project->source_from) ?></td>
                <td><?= H($project->bank_from) ?></td>
                <td style="vertical-align:middle">
                    <div class="pull-right">
                        <?php if($me->isAllowedTo('修改', $project)): ?>
                        <a class="btn no-padding" href="<?= URL("/project/profile/{$project->id}") ?>">
                            <i class="fa fa-edit fa-lg fa-fw"></i>
                        </a>
                        <?php endif; ?>
                        <a class="btn no-padding"
                            data-confirm="<?= H(T('您确认删除编号:project的项目?', [':project'=>$project->number])) ?>"
                            data-confirm-description="<?= H(T('点击确认后会删除项目信息, 请谨慎处理!')) ?>"
                            href="gini-ajax:AJAX/Project/Delete/<?= (int)$project->id ?>"
                            >
                            <i class="fa fa-trash-o fa-lg fa-fw"></i>
                        </a>
                    </div>
                </td>
            </tr>
            <?php endforeach; else: ?>
                <tr>
                    <td colspan="8" style="text-align: center;"><?= T('没有找到匹配的项目!') ?></td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>