<div class="container-fluid">
    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <?php 
            $me = _G('ME');
            if ($me->isAllowedTo('添加', 'project')):
        ?>
        <div class="btn-group mr-2" role="group" aria-label="First group">
            <button type="button" class="btn btn-dark" href="gini-ajax:AJAX/Project/Add">
                <i class="fa fa-plus"></i> 添加项目
            </button>
        </div>
        <?php endif; ?>
        <div class="btn-group mr-2" role="group">
            <a class="btn btn-primary" data-toggle="collapse" href="#searchBox" role="button" aria-expanded="<?= count($form) > 0 ? 'true' : 'false'?>" aria-controls="searchBox">
                <i class="fa fa-search"></i> 高级搜索
            </a>
        </div>
    </div>
    <div class="collapse multi-collapse <?= count($form) > 0 ? 'show' : ''?>" id="searchBox">
        <div class="hr"></div>
        <form method="POST" action="<?= URL('/project/'.$type) ?>">
            <div class="row">
                <div class="col">
                    <input type="text" class="form-control" name="number" placeholder="请输入项目编号" value="<?= $form['number'] ?>" />
                </div>
                <div class="col">
                    <input type="text" class="form-control" name="title" placeholder="请输入项目名称" value="<?= $form['title'] ?>" />
                </div>
                <div class="col">
                    <input type="text" class="form-control" name="source_from" placeholder="请输入业务来源" value="<?= $form['source_from'] ?>" />
                </div>
            </div>
            <div class="hr"></div>
            <div class="row">
                <div class="col">
                    <input type="text" class="form-control" name="bank_from" placeholder="请输入贷款银行" value="<?= $form['bank_from'] ?>" />
                </div>
                <div class="col"></div><div class="col"></div>
            </div>
            <div class="hr"></div>
            <div class="row">
                <div class="col">
                    <button class="btn btn-primary btn-raised" type="submit"><i class="fa fa-search fa-fw"></i> <?= H(T('搜索')) ?></button>
                </div>
            </div>
        </form>
    </div>
    <?= V('components/confirm') ?>
    <div class="hr"></div>
    <ul class="nav nav-tabs">
        <?php foreach(\Gini\ORM\Project::$TYPES as $key => $value):?>
            <li class="nav-item">
                <a class="nav-link <?= $type == $key ? 'active' : '' ?>" href="<?= URL('/project/'.$key) ?>"><?= $value ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="hr"></div>
    <?= $pagination ?>
    <table class="table table-light table-striped" id="project-table">
        <thead>
            <tr class="table-primary">
                <th scope="col">序号</th>
                <th scope="col">项目编号</th>
                <th scope="col">项目名称</th>
                <th scope="col">联系方式</th>
                <th scope="col">估价目的</th>
                <th scope="col">业务来源</th>
                <th scope="col">估价师</th>
                <th scope="col">状态</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <?php 
            $labels = [
                0 => 'badge-secondary',
                1 => 'badge-primary',
                2 => 'badge-info',
                3 => 'badge-dark',
                4 => 'badge-warning',
                5 => 'badge-success'
            ];
        ?>
        <tbody>
        <?php if (count($projects)): foreach($projects as $project): ?>
            <tr data-project-id="<?= intval($project->id) ?>">
                <td><span class="badge badge-dark"><?= str_pad($project->id, 6, '0', STR_PAD_LEFT) ?></span></td>
                <td><span class="badge badge-primary"><?= $project->number ?></span></td>
                <td><?= H($project->title) ?></td>
                <td><?= H($project->user_phone) ?></td>
                <td><?= H($project->target) ?></td>
                <td><?= H($project->source_from) ?></td>
                <td><small><?= H($project->assessor->id ? $project->assessor->name : '未指定') ?></small></td>
                <td>
                    <?php
                        $approval = a('approval')->whose('project')->is($project);
                    ?>
                    <span class="badge <?= $labels[(int)$approval->status] ?> white">
                        <?= \Gini\ORM\Approval::$APPROVAL_STATUS[(int)$approval->status] ?>
                    </span>
                </td>
                <td style="vertical-align:middle">
                    <div class="pull-right action-buttons">
                        <?php if($me->isAllowedTo('修改', $project)): ?>
                            <a class="btn no-padding" href="<?= URL("/project/profile/{$project->id}") ?>">
                                <i class="fa fa-eye fa-lg fa-fw"></i>
                            </a>
                        <?php endif; ?>
                        <a class="btn no-padding"
                            data-confirm="<?= H(T('您确认删除编号:project的项目?', [':project'=>$project->number])) ?>"
                            data-confirm-description="<?= H(T('点击确认后会删除项目信息, 请谨慎处理!')) ?>"
                            href="gini-ajax:AJAX/Project/Delete/<?= (int)$project->id ?>"
                            >
                            <i class="fa fa-trash-o fa-lg fa-fw"></i>
                        </a>
                    </div>
                </td>
            </tr>
            <?php endforeach; else: ?>
                <tr>
                    <td colspan="8" style="text-align: center;"><?= T('没有找到匹配的项目!') ?></td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
</div>