<div class="container-fluid">
    <?= V('components/confirm') ?>
    <div class="btn-toolbar" role="toolbar">
        <div class="btn-group mr-2" role="group">
            <a class="btn btn-primary btn-raised" href="<?= $project->archived() ? URL('/record') : URL('/project')?>">
                <i class="fa fa-arrow-left fa-fw"></i> <?= H(T('回到列表')) ?>
            </a>
        </div>
        <?php $me = _G('ME'); ?>
        <div class="btn-group mr-2" role="group" >
            <?php if ($me->isAllowedTo('指派派件员', $project)): ?>
                <button type="button" class="btn btn-dark" href="gini-ajax:AJAX/Project/Action/AddDispatcher/<?= $project->id ?>"><i class="fa fa-hand-o-left fa-fw"></i><?= T('指派派件员') ?></button>
            <?php endif; ?>
            <?php if ($me->isAllowedTo('指派估价员', $project)): ?>
                <button type="button" class="btn btn-secondary" href="gini-ajax:AJAX/Project/Action/AddAssessor/<?= $project->id ?>"><i class="fa fa-hand-o-left fa-fw"></i><?= T('指派估价师') ?></button>
            <?php endif; ?>
            <?php if ($me->isAllowedTo('指派查勘员', $project)): ?>
                <button type="button" class="btn btn-secondary" href="gini-ajax:AJAX/Project/Action/AddSurveyor/<?= $project->id ?>"><i class="fa fa-hand-o-left fa-fw"></i><?= T('指派查勘员') ?></button>
            <?php endif; ?>
        </div>
        <div class="btn-group mr-2" role="group" >
            <a class="btn btn-danger" href="<?= URL("/project/approval/{$project->id}")?>"><i class="fa fa-check fa-fw"></i><?= T('审核及模板信息') ?></a>
            <?php if ($me->isAllowedTo('打印报告', $project)): ?>
                <a class="btn btn-dark" href="gini-ajax:AJAX/Project/SelectTemplate/<?= $project->id ?>"><i class="fa fa-check fa-fw"></i><?= T('选择报告模板') ?></a>
                <a class="btn btn-secondary" href="gini-ajax:AJAX/Project/SelectPreEval/<?= $project->id ?>"><i class="fa fa-check fa-fw"></i><?= T('选择预评模板') ?></a>
            <?php endif; ?>
        </div>
        <div class="btn-group mr-2" role="group" >
            <?php if ($me->isAllowedTo('克隆项目', $project)): ?>
                <button type="button" class="btn btn-dark" href="gini-ajax:AJAX/Project/Clone/<?= $project->id ?>"><i class="fa fa-copy fa-fw"></i><?= T('克隆数据') ?></button>
            <?php endif; ?>
            <?php if ($me->isAllowedTo('归档', $project)): ?>
            <a class="btn btn-warning"
                data-confirm="<?= H(T('您确认归档此项目吗?')) ?>"
                data-confirm-description="<?= H(T('点击确认后会归档该项目信息, 请谨慎处理!')) ?>"
                href="gini-ajax:AJAX/Project/Archive/<?= (int)$project->id ?>"
                ><i class="fa fa-save fa-fw"></i><?= T('归档项目') ?></a>
            <?php endif; ?>
        </div>
    </div>
    <div class="hr_2"></div>
        <div class="row">
            <div class="col">
                <h5 data-toggle="tooltip" title="#001">
                    项目编号: <?= strtr(\Gini\Config::get('project.number_template'), [
                        '%year' => date('Y', strtotime($project->ctime)),
                        '%number' => $project->number
                    ])?>
                    <?php
                        $approval = a('approval')->whose('project')->is($project);
                    ?>
                    <span class="badge badge-warning white">
                        <?= \Gini\ORM\Approval::$APPROVAL_STATUS[(int)$approval->status] ?>
                    </span>
                </h5>
                <h5 data-toggle="tooltip" title="#002">项目名称: <?= T($project->title) ?></h5>
                <h5 data-toggle="tooltip" title="#003">备注信息: </h5>
                <div class="text-gray" ><?= str_replace(["\r\n", "\n", "\r"], "<br/>", H($project->source_description)) ?></div>
                <div class="hr_2"></div>
                <div class="btn-toolbar" role="toolbar">
                    <div class="btn-group mr-2" role="group">
                        <a class="btn btn-primary btn-raised" href="gini-ajax:ajax/project/description/<?= $project->id?>">
                            <i class="fa fa-eye fa-fw"></i> <?= H(T('查看备注')) ?>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col">
                <h5 class="card-title">操作信息: </h5>
                <div class="card news" style="height: 280px; overflow-y: auto;">
                    <div class="card-body">
                        <?php foreach (those('log')->whose('project')->is($project) as $log): ?>
                            <p class="card-text news-box">
                                <span class="description"><?= $log->ctime ?></span>
                                <?= $log->description ?>
                            </p>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    <div class="hr_2"></div>
    <ul class="nav nav-tabs nav-fill">
        <li class="nav-item">
            <a class="nav-link <?= $sub == 'user' ? 'active' : ''?>" href="<?= URL("/project/profile/{$project->id}/user")?>">估价委托人</a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?= $sub == 'target' ? 'active' : ''?>" href="<?= URL("/project/profile/{$project->id}/target")?>">估价目的</a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?= $sub == 'object' ? 'active' : ''?>" href="<?= URL("/project/profile/{$project->id}/object")?>">估价对象</a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?= $sub == 'result' ? 'active' : ''?>" href="<?= URL("/project/profile/{$project->id}/result")?>">估价结果</a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?= $sub == 'register' ? 'active' : ''?>" href="<?= URL("/project/profile/{$project->id}/register")?>">注册估价师</a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?= $sub == 'operation' ? 'active' : ''?>" href="<?= URL("/project/profile/{$project->id}/operation")?>">估价作业期</a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?= $sub == 'report' ? 'active' : ''?>" href="<?= URL("/project/profile/{$project->id}/report/comparison")?>">技术报告</a>
        </li>
        <li class="nav-item">
            <a class="nav-link <?= $sub == 'attachment' ? 'active' : ''?>" href="<?= URL("/project/profile/{$project->id}/attachment")?>">附件信息</a>
        </li>
    </ul>
    <?= V("projects/subtype/{$sub}", [
        'project' => $project,
        'subCat' => $subCat,
        'form' => $form
    ]) ?>
</div>
<script>
require(['main'], function($){
    $('body').bind('copy cut', function(e) {
        e.preventDefault()
    })
})
</script>