<div id="edit-user-role-modal" class="modal fade in">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title"><?= H(T('修改角色')) ?></h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body" style="padding-top:20px;">
            <form id="edit-user-role-form" method="POST" action="gini-ajax:ajax/user/editrole/<?= (int)$user->id ?>">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group form-group-lg">
                            <?php 
                                $roles = those('role');
                                $mineRoles = $user->roles()->get('role_id');
                                foreach ($roles as $role): 
                            ?>
                            <div class="form-check-inline">
                                <input class="form-check-input position-static" <?= in_array($role->id, $mineRoles) ? 'checked="checked"' : '' ?> type="checkbox" name="role[<?= $role->id ?>]">&#160;<?= T($role->name) ?>
                            </div>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary btn-raised" form="edit-user-role-form" type="submit"><i class="fa fa-plus fa-fw"></i> <?= H(T('修改')) ?></button>
            <button class="btn btn-secondary btn-raised" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times fa-fw "></i><?= H(T('关闭')) ?></button>
        </div>
    </div>
    </div>
</div>
<script data-ajax="true">
require(['main'], function($){

    var $modal = $('#edit-user-role-modal');
    $modal
    .on('hidden.bs.modal', function(){
        $modal.remove();
    })
    .modal();

    $('#edit-user-role-form').on('ajax-success', function(){
        $modal
        .removeAttr('id').modal('hide')
        .find('[id]').removeAttr('id');
    });

});
</script>