<div id="edit-user-modal" class="modal fade in">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <?php list($token, $backend) = \Gini\Auth::parseUserName($user->username); ?>
            <h4 class="modal-title"><?= H(T("修改人员({$token})密码信息")) ?></h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body" style="padding-top:20px;">
            <form id="edit-user-form" method="POST" action="gini-ajax:ajax/user/EditPwd/<?= (int)$user->id ?>">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group form-group-lg">
                            <?php if (isset($form['_errors']['password'])): ?>
                            <span class="badge badge-danger pull-right">
                                <?= H($form['_errors']['password']) ?>
                            </span>
                            <?php endif; ?>
                            <label class="control-label" for="password"><?= H(T('密码')) ?></label>
                            <input id="password" name="password" type="password" class="form-control <?= isset($form['_errors']['password']) ? ' is-invalid':'' ?>" autocomplete="off" value="<?= H($form['password']) ?>" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary btn-raised" form="edit-user-form" type="submit"><i class="fa fa-plus fa-fw"></i> <?= H(T('修改')) ?></button>
            <button class="btn btn-secondary btn-raised" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times fa-fw "></i><?= H(T('关闭')) ?></button>
        </div>
    </div>
    </div>
</div>
<script data-ajax="true">
require(['main'], function($){

    var $modal = $('#edit-user-modal');
    $modal
    .on('hidden.bs.modal', function(){
        $modal.remove();
    })
    .modal();

    $('#edit-user-form').on('ajax-success', function(){
        $modal
        .removeAttr('id').modal('hide')
        .find('[id]').removeAttr('id');
    });

});
</script>