<div class="container-fluid">
    <div class="card text-left bg-light">
        <div class="card-header">
            <?= T('估价机构信息') ?>
        </div>
        <div class="card-body">
            <?php
                $true_group = (array)Hub('template.group');
                $group = (array)\Gini\Config::get('project.group');
            ?>
            <form id="group-info-form" method="POST" action="<?= URL('/mine')?>">
                <div class="form-group row" data-toggle="tooltip" title="#0111"> 
                    <label for="name" class="col-sm-2 col-form-label">名称</label>
                    <div class="col-sm-10">
                        <input type="text" name="name" class="form-control" id="name" placeholder="<?= $group['name'] ?>" value="<?= $true_group['name']?>" />
                    </div>
                </div>
                <div class="form-group row" data-toggle="tooltip" title="#0112">
                    <label for="owner" class="col-sm-2 col-form-label">法定代表人</label>
                    <div class="col-sm-10">
                        <input type="text" name="owner" class="form-control" id="owner" placeholder="<?= $group['owner'] ?>" value="<?= $true_group['owner']?>" />
                    </div>
                </div>
                <div class="form-group row" data-toggle="tooltip" title="#0113">
                    <label for="address" class="col-sm-2 col-form-label">住所</label>
                    <div class="col-sm-10">
                        <input type="text" name="address" class="form-control" id="address" placeholder="<?= $group['address'] ?>" value="<?= $true_group['address']?>" />
                    </div>
                </div>
                <div class="form-group row" data-toggle="tooltip" title="#0114">
                    <label for="code" class="col-sm-2 col-form-label">统一社会用代码</label>
                    <div class="col-sm-10">
                        <input type="text" name="code" class="form-control" id="code" placeholder="<?= $group['code'] ?>" value="<?= $true_group['code']?>" />
                    </div>
                </div>
                <div class="form-group row" data-toggle="tooltip" title="#0115">
                    <label for="level" class="col-sm-2 col-form-label">备案等级</label>
                    <div class="col-sm-10">
                        <input type="text" name="level" class="form-control" id="level" placeholder="<?= $group['level'] ?>" value="<?= $true_group['level']?>" />
                    </div>
                </div>
                <div class="form-group row" data-toggle="tooltip" title="#0116">
                    <label for="number" class="col-sm-2 col-form-label">证书编号</label>
                    <div class="col-sm-10">
                        <input type="text" name="number" class="form-control" id="number" placeholder="<?= $group['number'] ?>" value="<?= $true_group['number']?>" />
                    </div>
                </div>
                <div class="form-group row" data-toggle="tooltip" title="#0117">
                    <label for="time_limit" class="col-sm-2 col-form-label">有效期限</label>
                    <div class="col-sm-10">
                        <input type="text" name="time_limit" class="form-control" id="time_limit" placeholder="<?= $group['time_limit'] ?>" value="<?= $true_group['time_limit']?>" />
                    </div>
                </div>
            </form>
        </div>
        <?php if (_G('ME')->isAllowedTo('修改', 'group')): ?>
        <div class="card-footer text-muted">
             <div class="btn-group mr-2" role="group" >
                <button form="group-info-form" type="submit" class="btn btn-primary"><i class="fa fa-save fa-fw"></i><?= T('保存信息') ?></button>
            </div>
        </div>
        <?php endif; ?>
    </div>
    <div class="hr_1"></div>
    <?php
        $true_policy = (array)Hub('template.policy');
        $policy = (array)\Gini\Config::get('project.policy');
    ?>
    <div class="card text-left bg-light">
        <div class="card-header">
            <?= T('政策模板信息') ?>
        </div>
        <div class="card-body">
            <form id="policy-info-form" method="POST" action="<?= URL('/mine')?>">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col row">
                            <label for="added_value" class="col-sm-6 col-form-label">增值税（%）</label>
                            <div class="col-sm-6">
                                <input type="text" name="added_value" class="form-control" id="added_value" placeholder="<?= $policy['added_value'] ?>" value="<?= $true_policy['added_value']?>" />
                            </div>
                        </div>
                        <div class="col row">
                            <label for="business_tax_value" class="col-sm-6 col-form-label">房产税（%）</label>
                            <div class="col-sm-6">
                                <input type="text" name="business_tax_value" class="form-control" id="business_tax_value" placeholder="<?= $policy['business_tax_value'] ?>" value="<?= $true_policy['business_tax_value']?>" />
                            </div>
                        </div>
                        <div class="col row">
                            <label for="banker_rate_value" class="col-sm-6 col-form-label">银行存款利率（%）</label>
                            <div class="col-sm-6">
                                <input type="text" name="banker_rate_value" class="form-control" id="banker_rate_value" placeholder="<?= $policy['banker_rate_value'] ?>" value="<?= $true_policy['banker_rate_value']?>" />
                            </div>
                        </div>
                    </div>
                    <div class="hr_1"></div>
                    <div class="row">
                        <div class="col row">
                            <label for="added_tax_value" class="col-sm-6 col-form-label">附加增值税（%）</label>
                            <div class="col-sm-6">
                                <input type="text" name="added_tax_value" class="form-control" id="added_tax_value" placeholder="<?= $policy['added_tax_value'] ?>" value="<?= $true_policy['added_tax_value']?>" />
                            </div>
                        </div>
                        <div class="col row"></div>
                        <div class="col row"></div>
                    </div>
                </div>
            </form>
        </div>
        <div class="card-footer text-muted">
             <div class="btn-group mr-2" role="group" >
                <button form="policy-info-form" type="submit" value="policy" class="btn btn-primary"><i class="fa fa-save fa-fw"></i><?= T('保存信息') ?></button>
            </div>
        </div>
    </div>
</div>