<div class="container-fluid">
    <div class="btn-toolbar" role="toolbar">
        <div class="btn-group mr-2" role="group">
            <a class="btn btn-primary btn-raised" href="<?= URL("/template")?>">
                <i class="fa fa-arrow-left fa-fw"></i> <?= H(T('回到列表')) ?>
            </a>
        </div>
        <div class="btn-group mr-2" role="group">
            <?= V('components/confirm') ?>
            <a class="btn btn-secondary btn-raised"
                data-confirm="<?= H(T('您确认删除模板:template?', [':template'=>$template->title])) ?>"
                data-confirm-description="<?= H(T('点击确认后会删除该用户信息, 请谨慎处理!')) ?>"
                href="gini-ajax:AJAX/Template/Delete/<?= (int)$template->id ?>/1">
                <i class="fa fa-trash-o fa-fw"></i> <?= T('删除模板') ?>
            </a>
            <button class="btn btn-dark btn-raised" form="edit-template-form" type="submit"><i class="fa fa-save fa-fw"></i> <?= H(T('保存模板')) ?></button>
        </div>
    </div>
    <form id="edit-template-form" method="POST" action="gini-ajax:ajax/template/edit/<?= (int)$template->id ?>">
        <div class="row">
            <div class="col-3">
                <div class="hr_2"></div>
                <p class="no-margin"><span class="description">*&#160;模板为固定的 Word 文档</span></p>
                <div class="hr"></div>
                <p class="no-margin"><span class="description">*&#160;模板内需要替换数据可以通过 %xx% 形式来进行表达, xx 为项目中字段名称，比如：</span></p>
                <p class="no-margin"><span class="description">&#160;&#160;%项目名称% 显示为估价对象中项目名称字段内容</span></p>
                <p class="no-margin"><span class="description">&#160;&#160;%实地查勘日期% 显示为估价作业期中实地查勘日期字段内容</span></p>
                <p class="no-margin"><span class="description">*&#160;由于委托人姓名和估价师姓名冲突，故此两栏信息中需要增加委托人、估价师等前缀，比如：</span></p>
                <p class="no-margin"><span class="description">&#160;&#160;%委托人姓名% 显示为估价委托人中姓名字段内容</span></p>
                <div class="hr"></div>
                <p class="no-margin"><span class="description">*&#160;如若需要后续进行内容修改可用 %input% 代替空模板内容</span></p>
            </div>
            <div class="col-6">
                <h5 class="text-center"><?= H($template->title) ?></h5>
                <div class="file-loading">
                    <input id="template-attachment" name="input[]" type="file" multiple />
                </div>
            </div>
            <div class="col-3"></div>
        </div>
    </form>
    <div class="hr_2"></div>
    <div class="hr_2"></div>
</div>
<?php /* ?>
<script>
(function($){
    KindEditor.ready(function(K) {
        var $edit = K.create('#editor', {
            filterMode: false,
            minHeight: 660,
            items: [
                'source', '|', 'justifyleft', 'justifycenter', 'justifyright',
                'justifyfull', 'insertorderedlist', 'insertunorderedlist', 'indent', 'outdent', '|',
                'formatblock', 'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold',
                'italic', 'underline', 'strikethrough', 'lineheight', '|', 'table', '|', 
                // 'image', 'multiimage', 'insertfile', 
                'link', 'unlink', 'media', 'flash', '|', 'fullscreen'
            ],
            resizeType: 2,
            uploadJson: 'ajax/template/uploadJson/' + <?= (int)$template->id ?>,
            basePath: 'assets/',
            themesPath: 'assets/css/',
            fontSizeTable: ['9px', '10px', '12px', '14px', '16px', '18px', '22px', '24px', '32px', '48px']
        })
        $edit.sync()
    })
})(jQuery)
</script>
<?php */ ?>
<script>
require(['main'], function($) {
    require(['fileinput', 'theme/fa/theme', 'locales/zh', 'css!../css/fileinput'], function() {
        $("#template-attachment").fileinput({
            dropZoneEnabled: true,
            showClose: false,
            language: "zh",
            theme: "fa",
            uploadUrl: "ajax/template/uploadAttachment/<?= $template->id ?>",
            deleteUrl: "ajax/template/deleteAttachment/<?= $template->id ?>",
            initialPreviewDownloadUrl: '<?= URL("template/downloadAttachment/{$template->id}")?>/{key}',
            overwriteInitial: false,
            initialPreview: JSON.parse('<?= json_encode($template->attachments("docx")) ?>'),
            initialPreviewConfig: JSON.parse('<?= json_encode($template->attachmentsConfig("docx")) ?>'),
            preferIconicPreview: true,
            maxFileCount: 1,
            allowedFileExtensions: ['docx'],
            dropZoneTitle: '请上传修改过标记的模板文件...',
            previewFileIconSettings: {
                'doc': '<i class="fa fa-file-word-o text-primary"></i>',
                'txt': '<i class="fa fa-file-text-o text-info"></i>',
                'xls': '<i class="fa fa-file-excel-o text-success"></i>'
            },
            previewFileExtSettings: {
                'doc': function(ext) {
                    return ext.match(/(doc|docx)$/i);
                },
                'xls': function(ext) {
                    return ext.match(/(xls|xlsx)$/i);
                },
                'txt': function(ext) {
                    return ext.match(/(txt|ini|csv|java|php|js|css|numbers|pages|md)$/i);
                }
            },
            layoutTemplates: {
                actionZoom: ''
            }
        })
    })
})
</script>