<div class="container-fluid">
    <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Toolbar with button groups">
        <?php
            $me = _G('ME');
            if ($me->isAllowedTo('添加', 'template')):
        ?>
        <div class="btn-group" role="group" aria-label="First group">
            <button type="button" class="btn btn-dark" href="gini-ajax:AJAX/Template/Add">
                <i class="fa fa-plus"></i>
                新模板
            </button>
        </div>
        <?php endif; ?>
        <form method="POST" action="<?= URL('/template')?>">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text" id="btnGroupAddon2">标题</div>
                </div>
                <input type="title" name="title" class="form-control" placeholder="请输入模板名称查找" aria-label="请输入模板名称查找" aria-describedby="btnGroupAddon2" value="<?= $form['title']?>">
            </div>
        </form>
    </div>
    <div class="hr_2"></div>
    <?= V('components/confirm') ?>
    <table class="table table-light table-striped table-hover table-sm" id="template-table">
        <thead>
            <tr class="table-primary">
                <th scope="col">模板编号</th>
                <th scope="col">模板标题</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
        <?php if (count($templates)):
            foreach($templates as $template):
        ?>
            <tr data-template-id="<?= intval($template->id) ?>">
                <td><span class="badge badge-dark"><?= str_pad($template->id, 6, 0, STR_PAD_LEFT) ?></span></td>
                <td><?= H($template->title) ?></td>
                <td>
                    <div class="pull-right">
                        <?php if ($me->isAllowedTo('修改', $template)): ?>
                        <a class="btn no-padding" href="<?= URL("/template/edit/{$template->id}")?>">
                            <i class="fa fa-edit fa-lg fa-fw"></i>
                        </a>
                        <?php endif; ?>
                        <?php if ($me->isAllowedTo('删除', $template)): ?>
                        <a class="btn no-padding"
                            data-confirm="<?= H(T('您确认删除模板:template?', [':template'=>$template->title])) ?>"
                            data-confirm-description="<?= H(T('点击确认后会删除该用户信息, 请谨慎处理!')) ?>"
                            href="gini-ajax:AJAX/Template/Delete/<?= (int)$template->id ?>"
                            >
                            <i class="fa fa-trash-o fa-lg fa-fw"></i>
                        </a>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; else: ?>
            <tr>
                <td colspan="5" style="text-align: center;"><?= T('没有找到匹配的模板信息!') ?></td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
</div>